# Generated by Django 2.1.7 on 2019-02-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='internal_reference',
            field=models.CharField(editable=False, max_length=100, verbose_name='Internal Reference'),
        ),
    ]
