# Generated by Django 2.1.7 on 2019-03-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_ocrtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrtext',
            name='execution_time',
            field=models.IntegerField(editable=False, null=True, verbose_name='Execution Time'),
        ),
    ]
